language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

after_success:
  - curl https://markov-chain.github.io/travis/documentation.sh | bash

env:
  global:
    - secure: szKxMnKMHYE3FxAhuSnx2+Q5Upzq2SLR1pcv9VQNSqrff5k7NQz1LCodHrkro+GEcO6EETh1J/YC4dfKpdyx2dV/2n/0u+ibypqB7I3BQetyypWKTuGylVqhTO8qyNO1b0iu8Fg9Fee6sSUu+kMlc0P11iECeINdhvzkZzPlNeo=

notifications:
  email: false
