[package]
name = "hotspot"
version = "0.4.2"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/markov-chain/hotspot"
homepage = "https://github.com/markov-chain/hotspot"
documentation = "https://markov-chain.github.io/hotspot"
description = "The package provides an interface to HotSpot."
build = "build.rs"

[dependencies]
libc = "*"
matrix = "0.13"

[dev-dependencies]
assert = "*"
