[package]
name = "hotspot"
version = "0.1.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/simulated-reality/hotspot"
homepage = "https://github.com/simulated-reality/hotspot"
documentation = "https://simulated-reality.github.io/hotspot"
description = """
The library constructs thermal RC circuits for multiprocessor systems based on
the block model of HotSpot.
"""
build = "build.rs"

[dependencies]
libc = "*"

[dev-dependencies]
assert = "*"
