[package]
name = "hotspot"
version = "0.2.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/markov-chain/hotspot"
homepage = "https://github.com/markov-chain/hotspot"
documentation = "https://markov-chain.github.io/hotspot"
description = """
The library constructs thermal RC circuits for multiprocessor systems based on
the block model of HotSpot."""
build = "build.rs"

[dependencies]
libc = "*"

[dev-dependencies]
assert = "*"
